config/routes.rb
Rails.application.routes.draw do
  root to: 'courses#index'

# Devise
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' },
                    controllers: {
                      omniauth_callbacks: "users/omniauth_callbacks",
                      sessions: "users/sessions",
                    }

# Site
  get 'minha-historia' => 'application#my_history', as: :my_history
  get 'sobre' => 'application#about', as: :about
  get 'contato' => 'application#contact', as: :contact

# SSL Acme challenge
  get '.well-known/acme-challenge/:id' => 'application#acme_challenge'

# Amazon SES bounce notification
  post 'amazon_sns/bounce', 'amazon_sns#bounce'


# Iugu Notifications
  post 'iugu/invoice/status_changed' => 'iugu#status_changed'

# Subscription
  get 'pioneiros' => 'subscriptions#pioneiros', as: :pioneiros
  get 'partiu-codar' => 'subscriptions#partiu_codar', as: :subscribe_step_1
  post 'nova-inscricao' => 'subscriptions#create', as: :create_subscription

# Sales pages
  get 'como-programar-do-zero(/:video_id)' => 'sales_pages#index', as: :sales

##################
# Student Routes #
##################

  scope 'cursos/:course_id' do
    get '/' => 'courses#show', as: :course
    get '/:lesson_id/:item_weight' => 'items#show', as: :course_item

    scope '/:lesson_id/:item_weight/post/:discussion_id' do
      get '/' => 'items#show', as: :discussion
      post '/comments' => 'items#create_comment', as: :create_comment
    end
  end

  scope 'questao/:item_id' do
    get 'novo-post' => 'discussions#new', as: :new_discussion
    post 'novo-post' => 'discussions#create', as: :discussions

    get '/:discussion_id/edit' => 'discussions#edit', as: :edit_discussion
    patch '/:discussion_id/edit' => 'discussions#update'
  end

  resources :items, only: [] do
    resources :answers, only: [:create]
    patch :mark_as_done
  end

  resources :users, only: [:update] do
    collection do
      get :edit_password
      patch :update_password

      get :profile
      patch :update_profile

      get :dashboard
      get :subscription
    end
  end

  get 'notifications/:id/redirect' => 'notifications#redirect', as: :notification_redirect

  resources :comments, only: [:edit, :update]

  resources :blog_posts, path: '/dev_questions', only: [:index, :new, :create, :show] do
    post :comments
  end
  # get '/blog_posts(/:id)' => 'blog_posts#index', as: :blog_post # precisa ficar depois

################
# Admin Routes #
################

  get 'admin' => 'admin#index'

  namespace :admin do
    resources :projects

    resources :courses do
      resources :lessons do
        patch :update_weight

        resources :items do
          patch :update_weight
        end
      end
    end

    resources :blog_posts do
      patch :approve
    end
  end

end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :item
  belongs_to :user
  has_many :comments, -> { order(:created_at) }, as: :commentable

  validates_presence_of :title, :text, :user, :item

  after_create :notify_admin

  # Slug
    extend FriendlyId
    friendly_id :slug_candidates, use: :slugged


  def belongs_to?(user)
    self.user.id == user.id
  end

private

  def slug_candidates
    [
      :title,
      [:title, :count_same_title],
    ]
  end

  def count_same_title
    Discussion.where(title: title).count
  end

  def notify_admin
    Notification.new_post(self)
  end

end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :require_subscription
  before_action :set_item
  before_action :set_discussion, only: [:edit, :update]
  before_action :check_discussion_user, only: [:edit, :update]

  def new
    @discussion = Discussion.new
  end

  def create
    @discussion = Discussion.new(discussion_params)
    @discussion.user = current_user
    @discussion.item = @item

    if @discussion.save
      redirect_to anchor_discussion_path(@discussion)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @discussion.update(discussion_params)
      redirect_to anchor_discussion_path(@discussion)
    else
      render :edit
    end
  end

private

  def discussion_params
    params.require(:discussion).permit(:title, :text)
  end

  def set_item
    @item = Item.find(params[:item_id])
  end

  def set_discussion
    @discussion = Discussion.friendly.find(params[:discussion_id])
  end

  def check_discussion_user
    return if current_user.admin?

    if !@discussion.belongs_to?(current_user)
      redirect_to anchor_discussion_path(@discussion)
    end
  end

end

app/helpers/discussions_helper.rb
module DiscussionsHelper

end

app/views/discussions/_comment.html.erb
<div class="box d-flex justify-content-between" id="<%= "comment_#{comment.id}" rescue nil %>">
  <aside>
    <div class="avatar"><%= image_tag comment&.user&.current_avatar ||'default_avatar.png' %></div>
  </aside>
  <div class="content">
    <article class="mb-4">
      <%= render_md comment.text %>
    </article>

    <footer class="d-flex justify-content-between align-items-center">
      <% if comment.belongs_to?(current_user) %>
        <div>
          <span class="badge badge-info">Eu</span>
          <small class="text-muted"><%= relative_time comment.created_at %></small>
        </div>

        <%= link_to edit_comment_path(comment), class: 'btn btn-sm btn-secondary' do %>
          <small><%= icon 'pencil' %> Editar</small>
        <% end %>
      <% else %>
        <div>
          <span class="blue"><%= comment.user.name %></span>
          <small class="text-muted"><%= relative_time comment.created_at %></small>
        </div>

        <% if current_user.admin? %>
          <%= link_to edit_comment_path(comment), class: 'btn btn-sm btn-secondary' do %>
            <small><%= icon 'pencil' %> Editar</small>
          <% end %>
        <% end %>
      <% end %>
    </footer>
  </div>
</div>

app/views/discussions/_discussion.html.erb
<div class="box d-flex justify-content-between">
  <aside>
    <div class="avatar"><%= image_tag discussion.user.current_avatar %></div>
  </aside>
  <div class="content">
    <article class="mb-4">
      <%= render_md discussion.text %>
    </article>

    <footer class="d-flex justify-content-between align-items-center">
      <% if discussion.belongs_to?(current_user) %>
        <div>
          <span class="badge badge-info">Eu</span>
          <small class="text-muted"><%= relative_time discussion.created_at %></small>
        </div>

        <%= link_to edit_discussion_path(@item, discussion), class: 'btn btn-sm btn-secondary' do %>
          <small><%= icon 'pencil' %> Editar</small>
        <% end %>
      <% else %>
        <div>
          <span class="blue"><%= discussion.user.name %></span>
          <small class="text-muted"><%= relative_time discussion.created_at %></small>
        </div>

        <% if current_user.admin? %>
          <%= link_to edit_discussion_path(@item, discussion), class: 'btn btn-sm btn-secondary' do %>
            <small><%= icon 'pencil' %> Editar</small>
          <% end %>
        <% end %>
      <% end %>
    </footer>

  </div>
</div>

app/views/discussions/_form.html.erb
<%= simple_form_for @discussion, url: @discussion.persisted? && edit_discussion_path(@item, @discussion) do |f| %>
  <%= f.input :title, label: 'Título' %>
  <%= f.input :text, label: 'Texto' %>
  <%= f.submit 'Postar', class: 'btn btn-primary' %>
  <%= link_to 'Voltar', @discussion.persisted? ? anchor_discussion_path(@discussion) : item_path(@item) %>
<% end %>

app/views/discussions/_index.html.erb
<section class="box d-flex justify-content-between align-items-center" id="posts-list">
  <h5 class="box-title">
    <%= image_tag 'yellow_post_icon.png' %>
    Perguntas e Comentários
  </h5>

  <%= link_to 'Faça uma Pergunta', new_discussion_path(item), class: 'btn btn-primary' %>
</section>

<div class="row">
  <div class="col-sm-4">
    <div class="box no-padding post-list">
      <% @item.discussions.each do |discussion| -%>
        <%= link_to discussion.title, anchor_discussion_path(discussion), class: "post d-flex align-items-baseline #{'active' if params[:discussion_id] == discussion.slug}" %>
      <% end %>
    </div>
  </div>


  <% if @active_discussion.present? %>
    <div class="col-sm 8 active-post">
      <%= render partial: 'discussions/discussion', locals: { discussion: @active_discussion } %>

      <% @active_discussion.comments.each do |comment| %>
        <%= render partial: 'discussions/comment', locals: { comment: comment, comment_id: comment.id } %>
      <% end %>

      <h5>Adicione uma resposta</h5>

      <div class="box d-flex justify-content-between">
        <aside>
          <div class="avatar"><%= image_tag current_user.current_avatar %></div>
        </aside>
        <div class="content">
          <%= simple_form_for @comment, url: create_comment_path do |f| %>
            <%= f.input :text, label: 'Digite sua resposta' %>
            <button type="submit" class="btn btn-primary">Enviar</button>
          <% end %>
        </div>
      </div>

    </div>
  <% end %>
</div>

app/views/discussions/edit.html.erb
<div class="container smallest">
  <div class="box bigger">
    <h3 class="mb-5">Edite sua Pergunta</h3>
    <%= render 'form' %>
  </div>
</div>

app/views/discussions/new.html.erb
<% title 'Faça uma pergunta' %>

<div class="container smallest">
  <div class="box bigger">
    <h3 class="mb-5">Faça sua pergunta</h3>
    <%= render 'form' %>
  </div>
</div>

app/views/discussions/show.html.erb
<section class="box d-flex justify-content-between align-items-center" id="posts-list">
  <h5 class="box-title">
    <%= image_tag 'yellow_post_icon.png' %>
    Perguntas e Comentários
  </h5>

  <%= link_to 'Faça uma Pergunta', new_discussion_path(@item), class: 'btn btn-primary' %>
</section>

<div class="row">
  <div class="col-sm-4">
    <div class="box no-padding post-list">
      <% @item.discussions.each do |discussion| %>
        <%= link_to anchor_discussion_path(discussion),
          class: "post #{'active' if params[:discussion_id] == discussion.slug}" do
        %>
          <div class="mb-2"><%= discussion.title %></div>
          <div class="d-flex align-items-center text-muted">
            <small class="mr-2">
              <%= icon 'user' %>
              <%= discussion.belongs_to?(current_user) ? 'Eu' : discussion.user.name %>
            </small>
            <small>
              <%= icon 'comment' %>
              <%= discussion.comments.count %>
            </small>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>


  <% if @active_discussion.present? %>
    <div class="col-sm-8 active-post">
      <%= render partial: 'discussions/discussion', locals: { discussion: @active_discussion } %>

      <% @active_discussion.comments.each do |comment| %>
        <%= render partial: 'discussions/comment', locals: { comment: comment } %>
      <% end %>

      <h5>Adicione uma resposta</h5>

      <%= render partial: 'comments/new', locals: { url: create_comment_path } %>
    </div>
  <% end %>
</div>