config/routes.rb
Rails.application.routes.draw do
  root to: 'courses#index'

# Devise
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' },
                    controllers: {
                      omniauth_callbacks: "users/omniauth_callbacks",
                      sessions: "users/sessions",
                    }

# Site
  get 'minha-historia' => 'application#my_history', as: :my_history
  get 'sobre' => 'application#about', as: :about
  get 'contato' => 'application#contact', as: :contact

# SSL Acme challenge
  get '.well-known/acme-challenge/:id' => 'application#acme_challenge'

# Amazon SES bounce notification
  post 'amazon_sns/bounce', 'amazon_sns#bounce'


# Iugu Notifications
  post 'iugu/invoice/status_changed' => 'iugu#status_changed'

# Subscription
  get 'pioneiros' => 'subscriptions#pioneiros', as: :pioneiros
  get 'partiu-codar' => 'subscriptions#partiu_codar', as: :subscribe_step_1
  post 'nova-inscricao' => 'subscriptions#create', as: :create_subscription

# Sales pages
  get 'como-programar-do-zero(/:video_id)' => 'sales_pages#index', as: :sales

##################
# Student Routes #
##################

  scope 'cursos/:course_id' do
    get '/' => 'courses#show', as: :course
    get '/:lesson_id/:item_weight' => 'items#show', as: :course_item

    scope '/:lesson_id/:item_weight/post/:discussion_id' do
      get '/' => 'items#show', as: :discussion
      post '/comments' => 'items#create_comment', as: :create_comment
    end
  end

  scope 'questao/:item_id' do
    get 'novo-post' => 'discussions#new', as: :new_discussion
    post 'novo-post' => 'discussions#create', as: :discussions

    get '/:discussion_id/edit' => 'discussions#edit', as: :edit_discussion
    patch '/:discussion_id/edit' => 'discussions#update'
  end

  resources :items, only: [] do
    resources :answers, only: [:create]
    patch :mark_as_done
  end

  resources :users, only: [:update] do
    collection do
      get :edit_password
      patch :update_password

      get :profile
      patch :update_profile

      get :dashboard
      get :subscription
    end
  end

  get 'notifications/:id/redirect' => 'notifications#redirect', as: :notification_redirect

  resources :comments, only: [:edit, :update]

  resources :blog_posts, path: '/dev_questions', only: [:index, :new, :create, :show] do
    post :comments
  end
  # get '/blog_posts(/:id)' => 'blog_posts#index', as: :blog_post # precisa ficar depois

################
# Admin Routes #
################

  get 'admin' => 'admin#index'

  namespace :admin do
    resources :projects

    resources :courses do
      resources :lessons do
        patch :update_weight

        resources :items do
          patch :update_weight
        end
      end
    end

    resources :blog_posts do
      patch :approve
    end
  end

end

app/models/project.rb
class Project < ApplicationRecord
  has_many :courses

  # Paperclip
    has_attached_file :image, path: "/projects-images/:id-:style.:extension"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  # Scopes
    scope :by_weight, -> { order(:weight) }

end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < AdminController
    before_action :set_project, only: [:edit, :update, :destroy]

    def index
      @projects = Project.by_weight
    end

    def new
      @project = Project.new(weight: Project.count)
    end

    def edit
    end

    def create
      @project = Project.new(project_params)

      if @project.save
        redirect_to admin_projects_url, notice: 'Project was successfully created.'
      else
        render :new
      end
    end

    def update
      if @project.update(project_params)
        redirect_to admin_projects_url, notice: 'Project was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @project.destroy
      redirect_to admin_projects_url, notice: 'Project was successfully destroyed.'
    end

  private

    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name, :image, :weight, :description)
    end

end

app/views/admin/projects/_form.html.erb
<% action = @project.new_record? ? admin_projects_path : admin_project_path(@project) %>

<%= simple_form_for @project, url: action do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :weight %>
    <%= f.input :image %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<%= link_to 'Back to Listing', admin_projects_path %>

app/views/admin/projects/edit.html.erb
<h1>Editando Projeto</h1>
<%= render 'form' %>

app/views/admin/projects/index.html.erb
<h5 class="mb-4">Projetos</h5>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th width="10%">Imagem</th>
      <th width="25%">Nome</th>
      <th width="30%">Descrição</th>
      <th width="10%"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= image_tag project.image %></td>
        <td>
          <%= project.weight %> - <%= project.name %>
          <br><br>
          <small class="text-muted"><%= project.courses.count %> cursos</small>
        </td>
        <td><%= project.description %></td>
        <td>
          <%= link_to 'Edit', edit_admin_project_path(project) %>
          |
          <%= link_to 'Delete', admin_project_path(project), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_admin_project_path %>

app/views/admin/projects/new.html.erb
<h1>Novo Projeto</h1>
<%= render 'form' %>