config/routes.rb
Rails.application.routes.draw do
  root to: 'courses#index'

# Devise
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' },
                    controllers: {
                      omniauth_callbacks: "users/omniauth_callbacks",
                      sessions: "users/sessions",
                    }

# Site
  get 'minha-historia' => 'application#my_history', as: :my_history
  get 'sobre' => 'application#about', as: :about
  get 'contato' => 'application#contact', as: :contact

# SSL Acme challenge
  get '.well-known/acme-challenge/:id' => 'application#acme_challenge'

# Amazon SES bounce notification
  post 'amazon_sns/bounce', 'amazon_sns#bounce'


# Iugu Notifications
  post 'iugu/invoice/status_changed' => 'iugu#status_changed'

# Subscription
  get 'pioneiros' => 'subscriptions#pioneiros', as: :pioneiros
  get 'partiu-codar' => 'subscriptions#partiu_codar', as: :subscribe_step_1
  post 'nova-inscricao' => 'subscriptions#create', as: :create_subscription

# Sales pages
  get 'como-programar-do-zero(/:video_id)' => 'sales_pages#index', as: :sales

##################
# Student Routes #
##################

  scope 'cursos/:course_id' do
    get '/' => 'courses#show', as: :course
    get '/:lesson_id/:item_weight' => 'items#show', as: :course_item

    scope '/:lesson_id/:item_weight/post/:discussion_id' do
      get '/' => 'items#show', as: :discussion
      post '/comments' => 'items#create_comment', as: :create_comment
    end
  end

  scope 'questao/:item_id' do
    get 'novo-post' => 'discussions#new', as: :new_discussion
    post 'novo-post' => 'discussions#create', as: :discussions

    get '/:discussion_id/edit' => 'discussions#edit', as: :edit_discussion
    patch '/:discussion_id/edit' => 'discussions#update'
  end

  resources :items, only: [] do
    resources :answers, only: [:create]
    patch :mark_as_done
  end

  resources :users, only: [:update] do
    collection do
      get :edit_password
      patch :update_password

      get :profile
      patch :update_profile

      get :dashboard
      get :subscription
    end
  end

  get 'notifications/:id/redirect' => 'notifications#redirect', as: :notification_redirect

  resources :comments, only: [:edit, :update]

  resources :blog_posts, path: '/dev_questions', only: [:index, :new, :create, :show] do
    post :comments
  end
  # get '/blog_posts(/:id)' => 'blog_posts#index', as: :blog_post # precisa ficar depois

################
# Admin Routes #
################

  get 'admin' => 'admin#index'

  namespace :admin do
    resources :projects

    resources :courses do
      resources :lessons do
        patch :update_weight

        resources :items do
          patch :update_weight
        end
      end
    end

    resources :blog_posts do
      patch :approve
    end
  end

end

app/controllers/admin/courses_controller.rb
class Admin::CoursesController < AdminController
    before_action :set_course, only: [:edit, :update, :destroy]

    def index
      @courses = Course.by_weight
    end

    def new
      @course = Course.new
    end

    def edit
    end

    def create
      @course = Course.new(course_params)

      if @course.save
        redirect_to admin_courses_url, notice: 'Course was successfully created.'
      else
        render :new
      end
    end

    def update
      if @course.update(course_params)
        redirect_to admin_courses_url, notice: 'Course was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @course.destroy
      redirect_to admin_courses_url, notice: 'Course was successfully destroyed.'
    end

  private

    def set_course
      @course = Course.friendly.find(params[:id])
    end

    def course_params
      params.require(:course).permit(:name, :image, :weight, :description, :available_at, :visible, :project_id)
    end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :require_subscription

  def index
    @projects = Project.by_weight
  end

  def show
    @course = Course.includes(lessons: :items).friendly.find(params[:course_id])
  end

end

app/views/courses/index.html.erb
<% title('Cursos') %>

<section>
  <div class="container smaller">
    <% @projects.each_with_index do |project, i| %>
      <% courses = project.courses.visible.by_weight %>

      <section class="box smaller">
        <h6 class="box-title">
          <%= image_tag 'map_marker.png' %>
          <span class="blue">Projeto <%= i + 1 %></span>
          <%= project.name %>
        </h6>

        <div id="course-map" class="d-flex flex-column align-items-center">
          <% courses.each_with_index do |course, index| %>
            <% if course.available? %>
              <%= link_to course_path(course), class: 'course available d-flex align-items-center' do %>
                <%= image_tag course.image, width: 50 %>
                <div class="text-left">
                  <%= course.name %>
                  <br>
                  <small class="text-success"><%= icon 'check' %> Disponível</small>
                </div>
              <% end %>
            <% else %>
              <span class="course unavailable d-flex align-items-center">
                <%= image_tag 'white_lock.png', width: 30 %>
                <div class="text-left">
                  <%= course.name %>
                  <% if course.show_available_at? %>
                    <br>
                    <small><%= icon 'calendar' %> <%= datefy course.available_at %></small>
                  <% end %>
                </div>
              </span>
            <% end %>

            <%= content_tag(:div, nil, class: :divider) if index+1 < courses.count  %>
          <% end %>
        </div>
      </section>
    <% end %>
  </div>
</section>

app/views/courses/show.html.erb
<% title(%{Curso de #{@course.name}}) %>
<% seo_description(%{Aprenda #{@course.name}, com as lições: #{@course.lessons.map(&:name).join(', ')}}) %>

<section class="container smaller">
  <div class="box">
    <div class="row">
      <div class="col-sm-3 text-center">
        <%= image_tag @course.image %>
      </div>
      <div class="col-sm-9">
        <h3 class="box-title"><%= @course.name %></h3>
        <p class="text-muted"><%= html_text @course.description %></p>
      </div>
    </div>
  </div>


  <% @course.lessons.each do |lesson| -%>
    <div class="box no-padding">
      <h4 class="box-title">
        Lição
        <%= lesson.weight %>:
        <span class="blue"><%= lesson.name %></span>
      </h4>

      <section class="questions-list">
        <% lesson.items.each do |item| %>
          <div class="item-link-wrapper">
            <%= link_to course_item_path(lesson_id: lesson.slug, item_weight: item.weight), class: 'item-link' do %>
              <%= item_icon(item) %>
              <span class="title"><%= item.title %></span>
            <% end %>

            <%= render partial: 'items/mark_as_done_buttons', locals: { item: item } %>
          </div>
        <% end -%>
      </section>
    </div>
  <% end -%>
</section>