config/routes.rb
Rails.application.routes.draw do
  root to: 'courses#index'

# Devise
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' },
                    controllers: {
                      omniauth_callbacks: "users/omniauth_callbacks",
                      sessions: "users/sessions",
                    }

# Site
  get 'minha-historia' => 'application#my_history', as: :my_history
  get 'sobre' => 'application#about', as: :about
  get 'contato' => 'application#contact', as: :contact

# SSL Acme challenge
  get '.well-known/acme-challenge/:id' => 'application#acme_challenge'

# Amazon SES bounce notification
  post 'amazon_sns/bounce', 'amazon_sns#bounce'


# Iugu Notifications
  post 'iugu/invoice/status_changed' => 'iugu#status_changed'

# Subscription
  get 'pioneiros' => 'subscriptions#pioneiros', as: :pioneiros
  get 'partiu-codar' => 'subscriptions#partiu_codar', as: :subscribe_step_1
  post 'nova-inscricao' => 'subscriptions#create', as: :create_subscription

# Sales pages
  get 'como-programar-do-zero(/:video_id)' => 'sales_pages#index', as: :sales

##################
# Student Routes #
##################

  scope 'cursos/:course_id' do
    get '/' => 'courses#show', as: :course
    get '/:lesson_id/:item_weight' => 'items#show', as: :course_item

    scope '/:lesson_id/:item_weight/post/:discussion_id' do
      get '/' => 'items#show', as: :discussion
      post '/comments' => 'items#create_comment', as: :create_comment
    end
  end

  scope 'questao/:item_id' do
    get 'novo-post' => 'discussions#new', as: :new_discussion
    post 'novo-post' => 'discussions#create', as: :discussions

    get '/:discussion_id/edit' => 'discussions#edit', as: :edit_discussion
    patch '/:discussion_id/edit' => 'discussions#update'
  end

  resources :items, only: [] do
    resources :answers, only: [:create]
    patch :mark_as_done
  end

  resources :users, only: [:update] do
    collection do
      get :edit_password
      patch :update_password

      get :profile
      patch :update_profile

      get :dashboard
      get :subscription
    end
  end

  get 'notifications/:id/redirect' => 'notifications#redirect', as: :notification_redirect

  resources :comments, only: [:edit, :update]

  resources :blog_posts, path: '/dev_questions', only: [:index, :new, :create, :show] do
    post :comments
  end
  # get '/blog_posts(/:id)' => 'blog_posts#index', as: :blog_post # precisa ficar depois

################
# Admin Routes #
################

  get 'admin' => 'admin#index'

  namespace :admin do
    resources :projects

    resources :courses do
      resources :lessons do
        patch :update_weight

        resources :items do
          patch :update_weight
        end
      end
    end

    resources :blog_posts do
      patch :approve
    end
  end

end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  include AASM

  belongs_to :user
  has_many :comments, -> { order(created_at: :asc) }, as: :commentable

  # Slug
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  # Scopes
  scope :published, -> { includes(:user).where('posted_at <= ?', Time.now).order(posted_at: :desc) }

  validates_presence_of :title
  accepts_nested_attributes_for :user

  after_create :notify_admin


  def belongs_to?(user)
    return false if self.user.blank?
    self.user.id == user.id
  end

  aasm do
    state :pending_approval, initial: true
    state :approved
    state :rejected

    event :approve { transitions from: :pending_approval, to: :approved }
    event :reject { transitions from: :pending_approval, to: :rejected }
  end

private

  def slug_candidates
    [
      :title,
      [:title, :count_same_title],
    ]
  end

  def count_same_title
    BlogPost.where(title: title).count
  end

  def notify_admin
    Notification.new_post(self)
  end

end

app/controllers/admin/blog_posts_controller.rb
class Admin::BlogPostsController < AdminController
    before_action :set_blog_post, only: [:edit, :update, :destroy, :approve]

    def index
      @blog_posts = BlogPost.order(aasm_state: :desc)
    end

    def new
      @blog_post = BlogPost.new
    end

    def edit
    end

    def create
      @blog_post = BlogPost.new(blog_post_params)
      @blog_post.approve
      @blog_post.posted_at = Time.now

      if @blog_post.save
        redirect_to admin_blog_posts_url, notice: 'BlogPost was successfully created.'
      else
        render :new
      end
    end

    def update
      if @blog_post.update(blog_post_params)
        redirect_to admin_blog_posts_url, notice: 'BlogPost was successfully updated.'
      else
        render :edit
      end
    end

    def approve
      if @blog_post.pending_approval?
        @blog_post.approve!
        Notification.blog_post_answered(@blog_post)
      end
      redirect_to admin_blog_posts_url
    end

    def destroy
      @blog_post.destroy
      redirect_to admin_blog_posts_url, notice: 'BlogPost was successfully destroyed.'
    end

  private

    def set_blog_post
      @blog_post = BlogPost.friendly.find(params[:id] || params[:blog_post_id])
    end

    def blog_post_params
      params.require(:blog_post).permit(:title, :text, :question_text, :posted_at)
    end

end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_current_post, only: [:show, :create, :comments, :index]

  def index
    redirect_to blog_post_path(@blog_posts.first)
  end

  def show
    # @comment = Comment.new(user: User.new)
    render :index
  end

  def new
    @blog_post = BlogPost.new(user: User.new)
  end

  def create
    @blog_post = BlogPost.new(blog_post_params.except(:user))
    @blog_post.posted_at = Time.now
    @blog_post.user = current_user || create_signin_user(blog_post_params[:user])

    if @blog_post.save
      redirect_to blog_post_path(@blog_post)
    else
      render :new
    end
  end

  def comments
    @comment = Comment.new(comment_params.except(:user))
    @comment.commentable = BlogPost.friendly.find(params[:blog_post_id])
    @comment.user = current_user || create_signin_user(comment_params[:user])

    if @comment.save
      redirect_to blog_post_path(@comment.commentable, anchor: "")
    else
      render :index
    end
  end


private

  def blog_post_params
    params.require(:blog_post).permit(:title, :question_text, user: [:name, :email, :password])
  end

  def comment_params
    params.require(:comment).permit(:text, user: [:name, :email, :password])
  end

  def create_signin_user(user_params)
    return if params[:receive_email] == '0'

    if params[:new_account] == '1'
      user = User.create(user_params)
    else
      user = User.where(email: user_params[:email]).first

      if !user || !user.valid_password?(user_params[:password])
        flash[:alert] = 'E-mail ou senha incorretos'
        return User.new
      end
    end

    sign_in(user) if user.errors.blank?
    user
  end

  def set_current_post
    @blog_posts = BlogPost.approved.published

    post_id = params[:blog_post_id] || params[:id]
    @current_post = BlogPost.friendly.find(post_id) if post_id.present?
  end

end

app/views/admin/blog_posts/_form.html.erb
<% action = @blog_post.new_record? ? admin_blog_posts_path : admin_blog_post_path(@blog_post) %>

<style>textarea { height: 20rem }</style>

<%= simple_form_for @blog_post, url: action do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :user, label: 'Pergunta feita por', disabled: true %>
    <%= f.input :title, label: 'Título' %>
    <%= f.input :question_text, label: 'Texto da pergunta' %>

    <%= f.input :text, label: 'Resposta' %>
    <%= f.input :posted_at, label: 'Postar em' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<%= link_to 'Back to Listing', admin_blog_posts_path %>

app/views/admin/blog_posts/edit.html.erb
<h1>Editing Blog Post</h1>
<%= render 'form' %>

app/views/admin/blog_posts/index.html.erb
<h1>Blog Posts</h1>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th width="25%">Título</th>
      <th width="15%">Postado em</th>
      <th width="15%">Status</th>
      <th width="30%">Feita por</th>
      <th width="10%"></th>
    </tr>
  </thead>

  <tbody>
    <% @blog_posts.each do |blog_post| %>
      <tr>
        <td><%= blog_post.title %></td>
        <td><%= relative_time blog_post.posted_at %></td>
        <td><%= blog_post.aasm_state %></td>
        <td><%= blog_post.user&.name %></td>
        <td>
          <% if blog_post.pending_approval? %>
            <%= link_to('Approve', admin_blog_post_approve_path(blog_post), method: :patch)  %>
            |
          <% end %>
          <%= link_to 'Edit', edit_admin_blog_post_path(blog_post) %>
          |
          <%= link_to 'Delete', admin_blog_post_path(blog_post), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog Post', new_admin_blog_post_path %>

app/views/admin/blog_posts/new.html.erb
<h1>New Blog Post</h1>
<%= render 'form' %>